### ISSUE TITLE
Pas de permissions pour push

### ISSUE THREAD

**Issue by KristerBC** [PolytechLyon/isi3-tp1-graph-clasen#1]
Monsieur,
Je n'arrive plus a push sur Girhub. Il dit que je n'ai pas les droits.
Ça marchait parfaitement au dernier TP.

Est-ce-que vous pouvez verifier que j'ai bien les droits ?

Cordialement,
Kristoffer.

**Comment by Slashgear** [comment]
Tu le fais avec kraken ? Si oui, ça peut probablement venir de ta configuration car tu as les droits en écritures ^^

**Comment by KristerBC** [comment]
Merci de votre réponse rapide.
En effet je l'utilise Gitkraken. Je viens essayer directement dans Intellij et ça marche.
