### ISSUE TITLE
Review Needed

### ISSUE THREAD

**Issue by Slashgear** [PolytechLyon/isi3-tp1-graph-clasen#2]
* Attention ce n'est pas à moi de créer cette issue

* [ ] ⚠️ les uml ne sont pas des UML de classe. Pouvez vous me les refaire afin que je puisse bien voir que vous avez compris le pattern Iterator et Adapter

* [ ] le code ça se nettoie https://github.com/PolytechLyon/isi3-tp1-graph-clasen/blob/bea7681e348ac894136178581b069625ad8a3803/src/main/java/graph/graphs/IUndirectedGraph.java#L6-L17

* [ ] la classe `Node` ne surchage pas la méthode `hashcode` Pouvez vous m'expliquer les impact ?

* 👍 Sympa les packages pour ranger un peu

**Comment by KristerBC** [comment]
Bonsoir,

J'ai supprimé le commentaire inutile dans https://github.com/PolytechLyon/isi3-tp1-graph-clasen/blob/bea7681e348ac894136178581b069625ad8a3803/src/main/java/graph/graphs/IUndirectedGraph.java#L6-L17

Est-ce-que Intellij peut faire des UML de classe automatiquement, ou faut-il les faire à la main ?

Explication de hashCode :
Si on a deux objets Java et on les compare avec on a
obj1 == obj2 | java l'interprete comme | obj1.hashCode() == obj2.hashCode()
Normalement java cree un hash en prenant tous les membres de la classe, mais dans notre car, on veut juste comparer les uniqueIDs. C'est pour cela que l'on surcharge hashCode pour que java ne compare que les uniqueIDs... car on on utilise cette comparaison de deux Nodes dans les iterateurs en utilisant le la fonction Collections.Contains

**Comment by Slashgear** [comment]
IntelliJ ne fait pas de Super UML de classe

En général moi j'utilisais Dia pour faire mes UML.
